export const authConstants = {
    LOGIN_REQUEST: "LOGIN_REQUEST",
    LOGIN_SUCCESS: "LOGIN_SUCCESS",
    LOGIN_FAILURE: "LOGIN_FAILURE",
  
    LOGOUT_REQUEST: "LOGOUT_REQUEST",
    LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
    LOGOUT_FAILURE: "LOGOUT_FAILURE",
  
    REGISTER_REQUEST: "REGISTER_REQUEST",
    REGISTER_SUCCESS: "REGISTER_SUCCESS",
    REGISTER_FAILURE: "REGISTER_FAILURE",
};
  

export const candidateConstants = {
    GET_CANDIDATE_REQUEST: "GET_CANDIDATE_REQUEST",
    GET_CANDIDATE_SUCCESS: "GET_CANDIDATE_SUCCESS",
    GET_CANDIDATE_FAILURE: "GET_CANDIDATE_FAILURE",
};
  

export const storeSelectedDataConstants = {
    STORE_SELECTED_CANDIDATE_DATA_REQUEST: "STORE_SELECTED_CANDIDATE_DATA_REQUEST",
    STORE_SELECTED_CANDIDATE_DATA_SUCCESS: "STORE_SELECTED_CANDIDATE_DATA_SUCCESS",
    STORE_SELECTED_CANDIDATE_DATA_FAILURE: "STORE_SELECTED_CANDIDATE_DATA_FAILURE",
};

export const minerConstants = {
    GET_DATA_REQUEST_PENDING: "GET_DATA_REQUEST_PENDING",
    GET_DATA_SUCCESS_PENDING: "GET_DATA_SUCCESS_PENDING",
    GET_DATA_FAILURE_PENDING: "GET_DATA_FAILURE_PENDING",

    GET_DATA_REQUEST_VERIFIED: "GET_DATA_REQUEST_VERIFIED",
    GET_DATA_SUCCESS_VERIFIED: "GET_DATA_SUCCESS_VERIFIED",
    GET_DATA_FAILURE_VERIFIED: "GET_DATA_FAILURE_VERIFIED",

    GET_DATA_REQUEST_CANCELLED: "GET_DATA_REQUEST_CANCELLED",
    GET_DATA_SUCCESS_CANCELLED: "GET_DATA_SUCCESS_CANCELLED",
    GET_DATA_FAILURE_CANCELLED: "GET_DATA_FAILURE_CANCELLED",

    VERIFY_DATA_REQUEST: "VERIFY_DATA_REQUEST",
    VERIFY_DATA_SUCCESS: "VERIFY_DATA_SUCCESS",
    VERIFY_DATA_FAILURE: "VERIFY_DATA_FAILURE",

    CANCELLED_DATA_REQUEST: "CANCELLED_DATA_REQUEST",
    CANCELLED_DATA_SUCCESS: "CANCELLED_DATA_SUCCESS",
    CANCELLED_DATA_FAILURE: "CANCELLED_DATA_FAILURE",
}